{% set version = "0.1.10" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggvenn
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggvenn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggvenn/ggvenn_{{ version }}.tar.gz
  sha256: cde116f117266cca27d8cd20205512e602c23514db6d97caaa950b9b21fa873e

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-ggplot2
  run:
    - r-base
    - r-dplyr
    - r-ggplot2

test:
  commands:
    - $R -e "library('ggvenn')"           # [not win]
    - "\"%R%\" -e \"library('ggvenn')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ggvenn
  license: MIT
  summary: An easy-to-use way to draw pretty venn diagram by 'ggplot2'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggvenn
# Title: Draw Venn Diagram by 'ggplot2'
# Version: 0.1.9
# Authors@R: person(given = "Linlin", family = "Yan", role = c("aut", "cre"), email = "yanlinlin82@gmail.com", comment = c(ORCID = "0000-0002-4990-6239"))
# Author: Linlin Yan [aut, cre] (<https://orcid.org/0000-0002-4990-6239>)
# Maintainer: Linlin Yan <yanlinlin82@gmail.com>
# Description: An easy-to-use way to draw pretty venn diagram by 'ggplot2'.
# Depends: dplyr, grid, ggplot2
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2021-06-29 04:57:58 UTC; yanll
# Repository: CRAN
# Date/Publication: 2021-06-29 05:20:07 UTC
